<?php
/**
 * Created by PhpStorm.
 * User: Sinri
 * Date: 2017/11/16
 * Time: 14:47
 */

namespace sinri\PageCamera\command;


use sinri\enoch\core\Enos;
use sinri\PageCamera\library\Task;

class TestCommand extends Enos
{

    /**
     * If keep $keyChain as null, return the whole config array;
     * If give $keyChain as array, it should work to return as
     * `$this->helper->safeReadNDArray($config,$keyChain,$default);`.
     * @param null|array $keyChain
     * @param null|mixed $default
     * @return array
     */
    protected function readConfig($keyChain = null, $default = null)
    {
        // TODO: Implement readConfig() method.
        return [];
    }

    public function actionDefault()
    {
        parent::actionDefault(); // TODO: Change the autogenerated stub
    }

    public function actionTestTakePhoto()
    {
        $task = new Task();
        $task->setDelay(15000);
        $task->setOutputDir('/opt/chrome_headless_test');
        $task->setUrl("https://freeplus.tmall.com/shop/view_shop.htm?&user_number_id=2646612614");

        $output = $task->takePhoto();
        echo "OUTPUT: " . $output . PHP_EOL;
    }
}